"""Branded 5-sheet Excel report generator.

Sheets:
  1. Summary          party / section / quarter mini-tables + total TDS
  2. Entry-level      one row per expense with TDS calc + resolved flag note
  3. Flagged          unresolved flags, one row each with reason + context
  4. Deposit Schedule quarter-wise TDS with Rule 30 due dates
  5. Lekha AI Recons  marketing page listing all 15 reconciliation modules

Branding: accent #467273 header bar + Lekha AI footer on every sheet.
Indian number formatting (#,##,##0.00) for all rupee columns.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date, datetime
from io import BytesIO
from pathlib import Path
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from lekha_catalogue import LEKHA_RECONS
from reports import build_views
from tds_knowledge.pan_utils import normalize_name
from tds_knowledge.thresholds import get_deposit_due_date, get_fy_label, get_quarter

# ── Colour palette mirrors frontend index.css tokens ──
ACCENT = "FF467273"
ACCENT_SOFT = "FFE3EBEB"
TEXT_MUTED = "FF5E6C84"
BORDER = "FFDFE1E6"
BG_ROW_ALT = "FFF7F8FA"
ORANGE = "FFEA580C"
GREEN = "FF16A34A"

# ── Fonts ──
FONT_BRAND = Font(name="Inter", size=14, bold=True, color="FFFFFFFF")
FONT_SUB = Font(name="Inter", size=10, color="FFFFFFFF")
FONT_H2 = Font(name="Inter", size=12, bold=True, color="FF1A1A2E")
FONT_TH = Font(name="Inter", size=10, bold=True, color=TEXT_MUTED)
FONT_TD = Font(name="Inter", size=10, color="FF1A1A2E")
FONT_TD_ACCENT = Font(name="Inter", size=10, bold=True, color=ACCENT)
FONT_MONO = Font(name="Consolas", size=10, color="FF1A1A2E")
FONT_FOOT = Font(name="Inter", size=9, italic=True, color=TEXT_MUTED)

# ── Fills / borders ──
FILL_ACCENT = PatternFill("solid", fgColor=ACCENT)
FILL_SUB = PatternFill("solid", fgColor=ACCENT_SOFT)
FILL_ALT = PatternFill("solid", fgColor=BG_ROW_ALT)
THIN = Side(style="thin", color=BORDER)
BOX = Border(top=THIN, bottom=THIN, left=THIN, right=THIN)

INR_FMT = '_-"₹"* #,##,##0.00_-;-"₹"* #,##,##0.00_-;_-"₹"* "-"??_-;_-@_-'
INT_FMT = "#,##,##0"


def _safe_date(raw: str | None) -> date | None:
    if not raw:
        return None
    try:
        return datetime.fromisoformat(str(raw)).date()
    except ValueError:
        return None


def _brand_header(ws: Worksheet, title: str, subtitle: str = "", cols: int = 6) -> int:
    """Write the 2-row Lekha-branded header. Returns the next free row index."""
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=cols)
    cell = ws.cell(row=1, column=1, value=f"Lekha AI  ·  {title}")
    cell.font = FONT_BRAND
    cell.fill = FILL_ACCENT
    cell.alignment = Alignment(horizontal="left", vertical="center", indent=1)
    ws.row_dimensions[1].height = 28

    if subtitle:
        ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=cols)
        cell = ws.cell(row=2, column=1, value=subtitle)
        cell.font = FONT_SUB
        cell.fill = FILL_ACCENT
        cell.alignment = Alignment(horizontal="left", vertical="center", indent=1)
        ws.row_dimensions[2].height = 18
        return 4  # skip a blank row

    return 3


def _footer(ws: Worksheet, row: int, cols: int = 6) -> None:
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=cols)
    cell = ws.cell(
        row=row,
        column=1,
        value=(
            "Generated by Lekha AI · TDS Calculator. Computational assistance only — "
            "final TDS responsibility rests with the deductor. scaleupcfo.in"
        ),
    )
    cell.font = FONT_FOOT
    cell.alignment = Alignment(horizontal="left", vertical="center", indent=1)


def _write_header_row(ws: Worksheet, row: int, labels: list[str]) -> None:
    for col_idx, label in enumerate(labels, start=1):
        c = ws.cell(row=row, column=col_idx, value=label)
        c.font = FONT_TH
        c.fill = FILL_SUB
        c.alignment = Alignment(horizontal="left" if col_idx <= 2 else "right", vertical="center")
        c.border = BOX


def _write_data_row(
    ws: Worksheet,
    row: int,
    values: list[Any],
    numeric_cols: set[int] = frozenset(),
    accent_cols: set[int] = frozenset(),
    mono_cols: set[int] = frozenset(),
    alt: bool = False,
) -> None:
    for col_idx, value in enumerate(values, start=1):
        c = ws.cell(row=row, column=col_idx, value=value)
        if col_idx in mono_cols:
            c.font = FONT_MONO
        elif col_idx in accent_cols:
            c.font = FONT_TD_ACCENT
        else:
            c.font = FONT_TD
        c.alignment = Alignment(
            horizontal="right" if col_idx in numeric_cols else "left",
            vertical="center",
        )
        c.border = BOX
        if alt:
            c.fill = FILL_ALT
        if col_idx in numeric_cols:
            c.number_format = INR_FMT


def _autosize(ws: Worksheet, widths: list[int]) -> None:
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


# Totals row — visually distinct strip at the bottom of each table.
# `values` is the same shape as `_write_data_row`; pass "" / 0 in cells you don't sum.
FILL_TOTAL = PatternFill("solid", fgColor=ACCENT_SOFT)
FONT_TOTAL_LABEL = Font(name="Inter", size=10, bold=True, color="FF1A1A2E")
FONT_TOTAL_NUM = Font(name="Inter", size=10, bold=True, color=ACCENT)
TOTAL_TOP = Border(top=Side(style="medium", color=ACCENT), bottom=THIN, left=THIN, right=THIN)


def _write_totals_row(
    ws: Worksheet,
    row: int,
    values: list[Any],
    numeric_cols: set[int] = frozenset(),
    accent_cols: set[int] = frozenset(),
) -> None:
    """Render a bold totals row with an accent top border."""
    for col_idx, value in enumerate(values, start=1):
        c = ws.cell(row=row, column=col_idx, value=value)
        if col_idx in accent_cols:
            c.font = FONT_TOTAL_NUM
        else:
            c.font = FONT_TOTAL_LABEL
        c.alignment = Alignment(
            horizontal="right" if col_idx in numeric_cols else "left",
            vertical="center",
        )
        c.fill = FILL_TOTAL
        c.border = TOTAL_TOP
        if col_idx in numeric_cols:
            c.number_format = INR_FMT


# ──────────────────────────────────────────────────────────────────────
# Sheet builders
# ──────────────────────────────────────────────────────────────────────

def _sheet_summary(ws: Worksheet, payload: dict[str, Any]) -> None:
    views = payload["views"]
    totals = views["totals"]
    row = _brand_header(
        ws,
        "TDS Summary",
        f"Total TDS: ₹ {totals['total_tds']:,.2f}  ·  {totals['row_count']} rows  ·  "
        f"{len(views['party_view'])} vendors",
        cols=5,
    )

    # Party section
    ws.cell(row=row, column=1, value="By Party").font = FONT_H2
    row += 1
    _write_header_row(ws, row, ["Vendor", "PAN", "Amount Paid", "TDS", "Sections"])
    row += 1
    party_paid = 0.0
    party_tds = 0.0
    for i, p in enumerate(views["party_view"]):
        _write_data_row(
            ws,
            row,
            [p["vendor"], p["pan"], p["total_paid"], p["total_tds"], ", ".join(p["sections"])],
            numeric_cols={3, 4},
            accent_cols={4},
            mono_cols={2},
            alt=(i % 2 == 1),
        )
        party_paid += float(p["total_paid"] or 0)
        party_tds += float(p["total_tds"] or 0)
        row += 1
    _write_totals_row(
        ws, row,
        [f"Total · {len(views['party_view'])} vendors", "", round(party_paid, 2), round(party_tds, 2), ""],
        numeric_cols={3, 4},
        accent_cols={4},
    )
    row += 1
    row += 2

    # Section
    ws.cell(row=row, column=1, value="By Section").font = FONT_H2
    row += 1
    _write_header_row(ws, row, ["Section", "Base Amount", "TDS", "Rows", "Vendors"])
    row += 1
    sec_base = 0.0
    sec_tds = 0.0
    sec_rows = 0
    for i, s in enumerate(views["section_view"]):
        _write_data_row(
            ws,
            row,
            [s["section"], s["total_base"], s["total_tds"], s["row_count"], s["vendor_count"]],
            numeric_cols={2, 3, 4, 5},
            accent_cols={3},
            alt=(i % 2 == 1),
        )
        sec_base += float(s["total_base"] or 0)
        sec_tds += float(s["total_tds"] or 0)
        sec_rows += int(s["row_count"] or 0)
        row += 1
    _write_totals_row(
        ws, row,
        ["Total", round(sec_base, 2), round(sec_tds, 2), sec_rows, ""],
        numeric_cols={2, 3, 4},
        accent_cols={3},
    )
    row += 1
    row += 2

    # Quarter
    ws.cell(row=row, column=1, value="By Quarter").font = FONT_H2
    row += 1
    _write_header_row(ws, row, ["FY", "Quarter", "TDS", "Rows", "Deposit Due"])
    row += 1
    qtr_tds = 0.0
    qtr_rows = 0
    for i, q in enumerate(views["quarter_view"]):
        _write_data_row(
            ws,
            row,
            [q["fy"], q["quarter"], q["total_tds"], q["row_count"], ", ".join(q["deposit_due_dates"])],
            numeric_cols={3, 4},
            accent_cols={3},
            alt=(i % 2 == 1),
        )
        qtr_tds += float(q["total_tds"] or 0)
        qtr_rows += int(q["row_count"] or 0)
        row += 1
    _write_totals_row(
        ws, row,
        ["Total", "", round(qtr_tds, 2), qtr_rows, ""],
        numeric_cols={3, 4},
        accent_cols={3},
    )
    row += 1

    _footer(ws, row + 2, cols=5)
    _autosize(ws, [36, 18, 18, 14, 28])


def _sheet_entries(ws: Worksheet, payload: dict[str, Any]) -> None:
    row = _brand_header(
        ws,
        "Entry-level TDS",
        "One row per expense with computed section, rate, and TDS.",
        cols=9,
    )
    _write_header_row(
        ws,
        row,
        ["Row", "Date", "Vendor", "PAN", "Description", "Amount", "Section", "Rate %", "TDS"],
    )
    row += 1
    total_amount = 0.0
    total_tds = 0.0
    for i, r in enumerate(payload["results"]):
        resolution_suffix = " (resolved)" if r.get("resolved") else ""
        skip = r.get("skip_reason")
        section_label = (r.get("section") or ("—" if not skip else "exempt")) + resolution_suffix
        _write_data_row(
            ws,
            row,
            [
                r["row_id"],
                r.get("date") or "",
                r.get("vendor") or "",
                r.get("pan") or "",
                r.get("description") or "",
                r.get("amount") or 0,
                section_label,
                r.get("rate_pct") or 0,
                r.get("tds_amount") or 0,
            ],
            numeric_cols={6, 8, 9},
            accent_cols={9},
            mono_cols={4},
            alt=(i % 2 == 1),
        )
        total_amount += float(r.get("amount") or 0)
        total_tds += float(r.get("tds_amount") or 0)
        row += 1
    _write_totals_row(
        ws, row,
        [
            f"Total · {len(payload['results'])} rows",
            "", "", "", "",
            round(total_amount, 2),
            "", "",
            round(total_tds, 2),
        ],
        numeric_cols={6, 9},
        accent_cols={9},
    )
    row += 1

    _footer(ws, row + 2, cols=9)
    _autosize(ws, [6, 12, 28, 15, 34, 14, 16, 9, 14])


def _sheet_flagged(ws: Worksheet, payload: dict[str, Any]) -> None:
    row = _brand_header(
        ws,
        "Flagged Entries",
        "Rows that required human review. Resolutions applied from the Lekha review flow are shown.",
        cols=7,
    )
    _write_header_row(
        ws,
        row,
        ["Row", "Vendor", "Amount", "Description", "Reason", "Context", "Resolution"],
    )
    row += 1
    rows_by_id = {r["row_id"]: r for r in payload["results"]}

    # Include resolved rows (from results with `resolved=True`) plus outstanding flags[]
    seen = set()
    flagged_amount = 0.0
    flagged_tds = 0.0   # for resolved rows we know the TDS; pending shows blank in totals
    for r in payload["results"]:
        if r.get("resolved") or r.get("flags"):
            resolution = r.get("resolution_note") or ("—" if r.get("flags") else "")
            for reason in r.get("flags") or ["resolved"]:
                _write_data_row(
                    ws,
                    row,
                    [
                        r["row_id"],
                        r.get("vendor") or "",
                        r.get("amount") or 0,
                        r.get("description") or "",
                        reason,
                        _flag_human_context(reason, r),
                        resolution,
                    ],
                    numeric_cols={3},
                    alt=(len(seen) % 2 == 1),
                )
                if (r["row_id"], reason) not in seen:
                    flagged_amount += float(r.get("amount") or 0)
                    flagged_tds += float(r.get("tds_amount") or 0)
                seen.add((r["row_id"], reason))
                row += 1

    for f in payload.get("flags") or []:
        key = (f.get("row_id"), f.get("reason"))
        if key in seen:
            continue
        r = rows_by_id.get(f.get("row_id"), {})
        _write_data_row(
            ws,
            row,
            [
                f.get("row_id"),
                f.get("vendor") or r.get("vendor") or "",
                f.get("amount") or 0,
                f.get("description") or r.get("description") or "",
                f.get("reason"),
                f.get("context") or "",
                "Pending — review in app",
            ],
            numeric_cols={3},
            alt=(len(seen) % 2 == 1),
        )
        flagged_amount += float(f.get("amount") or 0)
        seen.add(key)
        row += 1

    if not seen:
        ws.cell(row=row, column=1, value="No flagged entries. All rows classified cleanly.").font = FONT_FOOT
        row += 1
    else:
        _write_totals_row(
            ws, row,
            [
                f"Total · {len(seen)} flagged",
                "",
                round(flagged_amount, 2),
                "",
                "",
                f"TDS computed: ₹ {flagged_tds:,.2f}",
                "",
            ],
            numeric_cols={3},
            accent_cols=set(),
        )
        row += 1

    _footer(ws, row + 2, cols=7)
    _autosize(ws, [6, 28, 14, 32, 22, 54, 34])


def _flag_human_context(reason: str, row: dict[str, Any]) -> str:
    if reason == "ambiguous_section":
        return f"Description '{row.get('description')}' could match multiple sections."
    if reason == "unknown_expense":
        return f"No TDS section matches '{row.get('description')}'."
    if reason == "missing_pan":
        return "PAN missing/invalid — Section 206AA decision applied."
    if reason == "near_threshold":
        return "Vendor aggregate close to annual threshold."
    if reason == "gst_inclusive_amount":
        return "Amount column appeared GST-inclusive."
    return reason


def _sheet_deposit_schedule(ws: Worksheet, payload: dict[str, Any]) -> None:
    row = _brand_header(
        ws,
        "Deposit Schedule",
        "TDS to deposit grouped by deduction month, with Rule 30 due dates.",
        cols=5,
    )
    _write_header_row(ws, row, ["Deduction Month", "FY / Quarter", "Rows", "TDS", "Deposit Due"])
    row += 1

    grouped: dict[tuple[str, str, date], dict[str, Any]] = {}
    for r in payload["results"]:
        d = _safe_date(r.get("date"))
        if not d or not r.get("tds_amount"):
            continue
        month_key = d.replace(day=1)
        key = (get_fy_label(d), get_quarter(d), month_key)
        g = grouped.setdefault(key, {"rows": 0, "tds": 0.0, "due": get_deposit_due_date(d)})
        g["rows"] += 1
        g["tds"] += float(r["tds_amount"])

    deposit_total_tds = 0.0
    deposit_total_rows = 0
    for i, ((fy, q, month), g) in enumerate(sorted(grouped.items())):
        _write_data_row(
            ws,
            row,
            [
                month.strftime("%b %Y"),
                f"{fy} · {q}",
                g["rows"],
                round(g["tds"], 2),
                g["due"].isoformat(),
            ],
            numeric_cols={3, 4},
            accent_cols={4},
            alt=(i % 2 == 1),
        )
        deposit_total_tds += float(g["tds"])
        deposit_total_rows += int(g["rows"])
        row += 1

    if not grouped:
        ws.cell(row=row, column=1, value="No TDS to deposit (all rows below threshold or unresolved).").font = FONT_FOOT
        row += 1
    else:
        _write_totals_row(
            ws, row,
            ["Total to deposit", "", deposit_total_rows, round(deposit_total_tds, 2), ""],
            numeric_cols={3, 4},
            accent_cols={4},
        )
        row += 1

    note_row = row + 2
    ws.cell(
        row=note_row,
        column=1,
        value=(
            "Rule 30 deposit rule: TDS deducted in March is due by 30 April; "
            "any other month is due by the 7th of the following month (non-government deductors)."
        ),
    ).font = FONT_FOOT
    ws.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=5)

    _footer(ws, note_row + 2, cols=5)
    _autosize(ws, [18, 22, 10, 18, 18])


def _sheet_lekha_recons(ws: Worksheet) -> None:
    row = _brand_header(
        ws,
        "15 Lekha AI Reconciliations",
        "Your TDS Calculator is one of 15 reconciliation modules. Explore the full suite at scaleupcfo.in.",
        cols=4,
    )
    _write_header_row(ws, row, ["#", "Domain", "Reconciliation", "Compliance"])
    row += 1

    # Group by flow for nicer reading
    by_flow: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in LEKHA_RECONS:
        by_flow[r["flow"]].append(r)
    order = ["Revenue", "Expense", "Balance Sheet"]

    index = 0
    for flow in order:
        items = by_flow.get(flow, [])
        if not items:
            continue
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=4)
        cell = ws.cell(row=row, column=1, value=f"— {flow} —")
        cell.font = Font(name="Inter", size=10, bold=True, color=ACCENT)
        cell.alignment = Alignment(horizontal="left", vertical="center", indent=1)
        row += 1
        for r in items:
            index += 1
            _write_data_row(
                ws,
                row,
                [index, r["domain"], r["title"], r["compliance"]],
                alt=(index % 2 == 1),
            )
            row += 1

    # CTA
    row += 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=4)
    cta = ws.cell(
        row=row,
        column=1,
        value=(
            "We automate the 10-day month-end close for CFOs in India, US, and UAE. "
            "Book a demo: scaleupcfo.in  ·  Powered by Lekha AI"
        ),
    )
    cta.font = Font(name="Inter", size=10, bold=True, color="FFFFFFFF")
    cta.fill = FILL_ACCENT
    cta.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[row].height = 26

    _footer(ws, row + 2, cols=4)
    _autosize(ws, [5, 14, 56, 18])


# ──────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────

def generate_report(tds_results: dict[str, Any]) -> bytes:
    """Build the 5-sheet workbook and return its bytes."""
    results = list(tds_results.get("results") or [])
    flags = list(tds_results.get("flags") or [])
    views = build_views(tds_results)
    payload = {"results": results, "flags": flags, "views": views}

    wb = Workbook()
    # Default sheet becomes Summary
    ws = wb.active
    ws.title = "Summary"
    _sheet_summary(ws, payload)

    _sheet_entries(wb.create_sheet("Entries"), payload)
    _sheet_flagged(wb.create_sheet("Flagged"), payload)
    _sheet_deposit_schedule(wb.create_sheet("Deposit Schedule"), payload)
    _sheet_lekha_recons(wb.create_sheet("Lekha AI · 15 Recons"))

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_report_file(tds_results: dict[str, Any], out_path: Path) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(generate_report(tds_results))
    return out_path
